---
- name: Ensure utils are installed
  become: yes
  package:
    name:
    - jq # JSON manipulation in terminal
    - the_silver_searcher # file search
    - httpie # better curl
    state: latest
  tags:
    - install