# Installs i3wm rice and tools
---
- name: Ensure i3-gaps is installed
  become: yes
  package:
    name: i3-gaps
    state: latest
  tags:
    - install
- name: Ensure tools are installed
  become: yes
  package:
    name:
        - i3lock-color # Lockscreen
        - flameshot # Screenshots
        - xorg-xbacklight # Control laptop lighting
        - dunst # notifications
        - rofi # Menus
        - i3status # status bar
        - picom # compositor
        - feh # Wallpaper
        - playerctl # Music control
    state: latest
  tags:
    - install

- name: Ensure i3 config path exists
  file:
    path: "/home/{{ ansible_user }}/.config/i3"
    state: directory
  tags:
  - user_config

- name: install i3 configuration
  template:
    src: .config/i3/config
    dest: "/home/{{ ansible_user }}/.config/i3/config"
  tags:
    - user_config
  notify:
    - reload i3 config

- name: install picom configuration
  template:
    src: .config/picom.conf
    dest: "/home/{{ ansible_user }}/.config/picom.conf"
  tags:
    - user_config
  notify:
    - reload i3 config
    - restart picom

- name: Ensure i3status config folder is present
  file:
    path: "/home/{{ ansible_user }}/.config/i3status"
    state: directory
  tags:
    - user_config
    
- name: Install i3status configuration
  template:
    src: .config/i3status/config
    dest: "/home/{{ ansible_user }}/.config/i3status/config"
  notify:
    - reload i3 config
  tags:
    - user_config

- name: Ensure dunst config folder is present
  file:
    path: "/home/{{ ansible_user }}/.config/dunst"
    state: directory
  tags:
    - user_config
    
- name: Install dunst configuration
  template:
    src: .config/dunst/dunstrc
    dest: "/home/{{ ansible_user }}/.config/dunst/dunstrc"
  tags:
    - user_config
