---
- include: prompt.yaml
- include: zsh.yaml

- name: Ensure .path file is loaded in .bash_profile
  lineinfile:
    line: "[[ -f ~/.path.sh ]] && . ~/.path.sh"
    path: ~/.bash_profile
  tags:
    - user_config

- name: Ensure .ssh/config is up to date
  template:
    src: .ssh/config
    dest: "/home/{{ ansible_user }}/.ssh/config"
  tags:
    - user_config

- name: Install utils
  become: yes
  package:
    name:
    - fzf
  tags:
  - install