# Load antigen
source /usr/share/zsh/share/antigen.zsh
# Starship shell
source <("/usr/bin/starship" init zsh --print-full-init)

# oh-my-zsh plugin
antigen use oh-my-zsh

# Enable fzf
antigen bundle fzf

# Set theme
antigen theme denysdovhan/spaceship-prompt

antigen apply

# Load custom paths
. $HOME/.path.sh
