---
- name: Ensure packages are installed
  shell: yay -S plasma kde-applications sddm --noconfirm
  tags:
    - install

- name: Ensure SDDM is enabled
  become: yes
  systemd:
    name: sddm
    force: yes # Overwrite any other DM
    enabled: yes
  tags:
    - config