---
- name: Ensure (n)vim is installed
  become: yes
  tags:
  - install
  package:
    name:
      - neovim
      - vim
    state: latest

- name: Ensure code is installed
  become: yes
  tags:
  - install
  package:
    name: code
    state: latest
