---
- name: Ensure (n)vim is installed
  become: yes
  tags:
  - install
  package:
    name:
      - neovim
      - vim
    state: latest

- name: Ensure code is installed
  tags:
  - install
  shell: yay -S --noconfirm visual-studio-code-bin

- name: Install code extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extenions }}"