---
- name: Archlinux hosts
  hosts: archlinux
  roles:
  - archlinux

- name: Services
  hosts: all
  roles:
    - services/ssh

- name: Config
  hosts: all
  roles:
    - config/path
    - config/timedatectl
- name: Software
  hosts: all
  roles:
    - software/git
    - software/shell

- name: Thinkpad
  hosts: thinkpad
  roles:
    #- software/plymouth
    - software/browsers
    - software/terminals
    - software/editors
    - software/networkmanager
    - software/kvm
    - software/im
    - software/openshift
    - devenv/frontend
    - devenv/golang
    # - name: rice/i3wm
    #   tags:
    #    - rice
    - name: rice/kde
      tags:
        - rice
