---
- name: Debug
  hosts: all
  roles:
  - name: debug
    tags:
    - debug

- name: Archlinux hosts
  hosts: archlinux
  roles:
  - archlinux

- name: Services
  hosts: all
  roles:
    - services/ssh

- name: Config
  hosts: all
  roles:
    - config/path
    - config/timedatectl
- name: Software
  hosts: all
  roles:
    - software/git
    - software/shell

- name: Thinkpad
  hosts: thinkpad
  roles:
    - software/browsers
    - software/terminals
    - software/editors
    - software/networkmanager
    - software/kvm
    - software/im
    - software/openshift
    - software/syncthing
    - software/keepassxc
    - software/docker
    - devenv/frontend
    - devenv/golang
    - name: rice/i3wm
      tags:
       - rice

- name: Deru
  hosts: deru
  roles:
    - software/browsers
    - software/terminals
    - software/editors
    - software/networkmanager
    - software/kvm
    - software/im
    - software/syncthing
    - name: rice/i3wm
      tags:
       - rice
